{
"name" : "Import & Export Bussiness Management System",
"version" : "1.0",
"author" : "Mindfire",
"website" : "www.mindfiresolutions.com",
"category" : "Unknown",
"description": """ OpenERP Import & Export Bussiness Management System """,
"depends" : ['base', 'crm', 'sale','account_voucher',],
"js": ['static/src/js/*.js'],
"css": ['static/src/css/*.css'],
"init_xml" : [ ],
"demo" : ['demo/shipment_config.xml',
        ],
"data" : ['shipment_menuitem.xml',
          'security/shipment_security.xml',
          'security/ir.model.access.csv',
          'shipment_view.xml',
          'port_view.xml',
          'charge_view.xml',
          'hts_view.xml',
          'partner_view.xml',
          'account_invoice_view.xml',
          'ramport_view.xml',
          'abi_results_view.xml',
          'driver_view.xml',
          'truck_view.xml',
          'statement_view.xml',
          'job_view.xml',
          'res_config_view.xml'
        ],
"installable": True
}